import fs from "node:fs/promises";
import path from "node:path";

export async function writeArtifacts(baseDir, payload) {
  await fs.mkdir(baseDir, { recursive: true });

  const patch = buildPatch(payload);

  const files = {
    "codex-task.md": payload.codexPrompt,
    "claude-repair-task.md": payload.claudePrompt,
    "pr-package.md": payload.prMarkdown,
    "execution.json": JSON.stringify(payload.executionPacket, null, 2),
    "changes.patch": patch
  };

  const written = [];
  for (const [name, content] of Object.entries(files)) {
    const fullPath = path.join(baseDir, name);
    await fs.writeFile(fullPath, content, "utf8");
    written.push(fullPath);
  }

  return written;
}

/**
 * Build a structured changes.patch file.
 * This is a human+machine-readable description of intended changes
 * in unified diff style. Apply manually or via `git apply` after
 * the Codex/Claude agent has generated real file contents.
 */
function buildPatch(payload) {
  const { executionPacket, codexPrompt, claudePrompt } = payload;
  const repo = executionPacket?.repo || "unknown/repo";
  const branch = executionPacket?.branch || "simba/patch";
  const now = new Date().toUTCString();

  const filesToCreate = (executionPacket?.files_to_create || []).map((f) =>
    [
      `diff --git a/${f} b/${f}`,
      `new file mode 100644`,
      `--- /dev/null`,
      `+++ b/${f}`,
      `@@ -0,0 +1 @@`,
      `+# Generated by Simba — see codex-task.md for full implementation prompt`
    ].join("\n")
  );

  const filesToModify = (executionPacket?.files_to_modify || []).map((f) =>
    [
      `diff --git a/${f} b/${f}`,
      `--- a/${f}`,
      `+++ b/${f}`,
      `@@ -1,1 +1,1 @@`,
      `-# existing content`,
      `+# modified by Simba task — see claude-repair-task.md for repair instructions`
    ].join("\n")
  );

  return [
    `# Simba Generated Patch`,
    `# Repo:   ${repo}`,
    `# Branch: ${branch}`,
    `# Date:   ${now}`,
    `#`,
    `# HOW TO APPLY`,
    `# 1. Run Codex or Claude with codex-task.md / claude-repair-task.md`,
    `# 2. Save the generated file contents to the paths below`,
    `# 3. git add . && git commit -m "${branch.replace("simba/", "feat: ")}"`,
    `# 4. git push origin ${branch}`,
    `# 5. Open the PR URL returned by Simba`,
    `#`,
    `# CODEX PROMPT SUMMARY`,
    `# ${codexPrompt.split("\n")[0]}`,
    `#`,
    `# CLAUDE REPAIR SUMMARY`,
    `# ${claudePrompt.split("\n")[0]}`,
    "",
    ...(filesToCreate.length ? filesToCreate : ["# No new files declared in execution packet"]),
    "",
    ...(filesToModify.length ? filesToModify : ["# No modified files declared in execution packet"])
  ].join("\n");
}
